name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push to Github Package Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Github Package Registry
        uses: docker/build-push-action@v1
        with:
          tag_ref: ${{ github.ref }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: phcarvalho/docker-image/teste
          tag_with_ref: true
          build-args: BUILD_NAME=PEDRO,SECRET_TEST=SECRET
